#!/bin/bash

echo "🔥 Firebase App Setup Script for Ordinary Gentlemen"
echo "=================================================="
echo ""

echo "📋 Step-by-Step Instructions:"
echo ""

echo "1️⃣ CREATE NEW FIREBASE PROJECT:"
echo "   • Go to: https://console.firebase.google.com/"
echo "   • Click 'Create a project'"
echo "   • Name: 'ordinary-gentlemen-v2' (or your preferred name)"
echo "   • Disable Google Analytics (optional)"
echo ""

echo "2️⃣ ADD WEB APP:"
echo "   • Click Web icon (</>)"
echo "   • App nickname: 'ordinary-gentlemen-web'"
echo "   • Enable Firebase Hosting: ❌ (NOT needed - you use Vercel)"
echo "   • Click 'Register app'"
echo ""

echo "3️⃣ COPY FIREBASE CONFIG:"
echo "   • Copy the config object that looks like this:"
echo "   • apiKey: 'AIzaSy...'"
echo "   • authDomain: 'project.firebaseapp.com'"
echo "   • projectId: 'project-id'"
echo "   • storageBucket: 'project.appspot.com'"
echo "   • messagingSenderId: '123456789'"
echo "   • appId: '1:123456789:web:abc123'"
echo ""

echo "4️⃣ ENABLE AUTHENTICATION:"
echo "   • Left sidebar → Authentication"
echo "   • Click 'Get started'"
echo "   • Sign-in method tab → Google"
echo "   • Enable Google sign-in"
echo "   • Set project support email"
echo "   • Click 'Save'"
echo ""

echo "5️⃣ CREATE FIRESTORE DATABASE:"
echo "   • Left sidebar → Firestore Database"
echo "   • Click 'Create database'"
echo "   • Start in test mode"
echo "   • Choose location (closest to users)"
echo ""

echo "6️⃣ CREATE WHITELIST COLLECTION:"
echo "   • Click 'Start collection'"
echo "   • Collection ID: 'whitelist'"
echo "   • Document ID: 'nik.desai87@gmail.com'"
echo "   • Add fields:"
echo "     - manager_fplid: [your FPL ID]"
echo "     - isAdmin: true"
echo "   • Add another document: 'desainikunj234@gmail.com'"
echo "     - manager_fplid: [test FPL ID]"
echo "     - isAdmin: false"
echo ""

echo "7️⃣ UPDATE ENVIRONMENT VARIABLES:"
echo "   • Create/update .env.local file with new Firebase config"
echo "   • Restart your development server"
echo ""

echo "8️⃣ TEST AUTHENTICATION:"
echo "   • Try logging in with both emails"
echo "   • Both should work if in whitelist"
echo ""

echo "🔧 Troubleshooting Tips:"
echo "   • Ensure Google sign-in is enabled"
echo "   • Check that domain restrictions allow localhost"
echo "   • Verify Firestore rules allow read access"
echo "   • Check browser console for errors"
echo ""

echo "✅ Setup Complete! Your new Firebase app should work for all whitelisted users."
